language: python
cache: pip
sudo: required


python:
  - "3.5"


before_install:
  - pip install -U pip
  - pip install wheel
  - pip install coveralls
  - sudo apt-get update


env:
  global:
    - KERAS_BACKEND=theano
    - PIP_WHEEL_DIR=$HOME/.cache/pip/wheels
    - PIP_FIND_LINKS=file://$HOME/.cache/pip/wheels


install:
  - pip wheel -r requirements.txt
  - pip install -r requirements.txt
  - sudo pip install keras


script:
  - THEANO_FLAGS='gcc.cxxflags="-march=core2"' py.test . --cov=./
  - flake8 ./


after_success:
  - coveralls
